USE [master]
GO
ALTER DATABASE LSJX SET RECOVERY SIMPLE WITH NO_WAIT
GO
ALTER DATABASE LSJX SET RECOVERY SIMPLE  
GO
USE LSJX 
GO
DBCC SHRINKFILE (N'Leader_Log' , 11, TRUNCATEONLY)
GO
USE [master]
GO
ALTER DATABASE LSJX SET RECOVERY FULL WITH NO_WAIT
GO
ALTER DATABASE LSJX SET RECOVERY FULL  
GO