
DELETE FROM BOMCB
INSERT INTO BOMCB SELECT * FROM [192.168.0.99].[COMFORT].dbo.BOMCB

DELETE FROM BOMMC
INSERT INTO BOMMC SELECT * FROM [192.168.0.99].[COMFORT].dbo.BOMMC

DELETE FROM BOMMD
INSERT INTO BOMMD SELECT * FROM [192.168.0.99].[COMFORT].dbo.BOMMD


-- 客户信息
DELETE FROM COPMA
INSERT INTO COPMA SELECT * FROM [192.168.0.99].[COMFORT].dbo.PURMA


-- 客户订单
DELETE FROM COPTC
INSERT INTO COPTC SELECT * FROM [192.168.0.99].[COMFORT].dbo.COPTC

DELETE FROM COPTD
INSERT INTO COPTD SELECT * FROM [192.168.0.99].[COMFORT].dbo.COPTD


-- PDA临时表
DELETE FROM LL_LYXA
DELETE FROM JH_LYXA



