
SELECT RTRIM(WORKLOG.STATION) AS 计算机名, RTRIM(WORKLOG2.IP) AS IP, CONVERT(VARCHAR(20), WORKLOG2.DT, 120) AS 最后程序打开时间, UPGRADELOG.DT AS 最后更新时间 FROM 
(
	SELECT CLIENTIP AS IP, MAX(DTSTART) AS DT FROM DSCSYS.dbo.WORKLOG GROUP BY CLIENTIP
) AS WORKLOG2
INNER JOIN DSCSYS.dbo.WORKLOG ON WORKLOG.CLIENTIP = WORKLOG2.IP AND WORKLOG2.DT = WORKLOG.DTSTART
LEFT JOIN 
(
	SELECT IpAddress AS IP, MAX(UpgradeDateTime) AS DT FROM YiFeiPublish.dbo.UpgradeLog GROUP BY IpAddress
) AS UPGRADELOG ON WORKLOG2.IP = UPGRADELOG.IP

WHERE 1=1
AND WORKLOG2.DT > DATEADD(DAY, -30, GETDATE())
AND DATEDIFF(DAY, CONVERT(DATE, UPGRADELOG.DT, 120), CONVERT(DATE, WORKLOG2.DT, 120)) > 0
-- AND WORKLOG2.IP = '192.168.1.36'
AND WORKLOG.STATION NOT LIKE '%TEST%'
-- AND WORKLOG.STATION LIKE '%CWB%'

ORDER BY WORKLOG.STATION