
-- 查询用户权限显示到界面
SELECT (CASE WHEN U.Permission_ID IS NULL THEN 0 ELSE 1 END), B.Name FROM WG_PERM_BASE AS B
LEFT JOIN WG_PERM_USER AS U ON B.K_ID = U.Permission_ID AND U.U_ID = '000960'
WHERE 1=1
ORDER BY B.K_ID