
-- 修改单头单身创建时间

SELECT TC001, TC002, TC003, 
A.CREATE_DATE AC, A.MODI_DATE AM, 
B.CREATE_DATE BC, B.MODI_DATE BM, 
RTRIM(TC003)+SUBSTRING(RTRIM(A.CREATE_DATE), 9, 9) ACN, 
(CASE WHEN RTRIM(A.MODI_DATE) = '' THEN A.MODI_DATE ELSE RTRIM(TC003)+SUBSTRING(RTRIM(A.MODI_DATE), 9, 9) END) AMN,
RTRIM(TC003)+SUBSTRING(RTRIM(B.CREATE_DATE), 9, 9) BCN, 
(CASE WHEN RTRIM(B.MODI_DATE) = '' THEN B.MODI_DATE ELSE RTRIM(TC003)+SUBSTRING(RTRIM(B.MODI_DATE), 9, 9) END) BMN
 
-- UPDATE PURTA SET PURTA.CREATE_DATE = RTRIM(TC003)+SUBSTRING(RTRIM(A.CREATE_DATE), 9, 9), PURTA.MODI_DATE = (CASE WHEN RTRIM(A.MODI_DATE) = '' THEN A.MODI_DATE ELSE RTRIM(TC003)+SUBSTRING(RTRIM(A.MODI_DATE), 9, 9) END)

-- UPDATE PURTB SET PURTB.CREATE_DATE = RTRIM(TC003)+SUBSTRING(RTRIM(B.CREATE_DATE), 9, 9), PURTB.MODI_DATE = (CASE WHEN RTRIM(B.MODI_DATE) = '' THEN B.MODI_DATE ELSE RTRIM(TC003)+SUBSTRING(RTRIM(B.MODI_DATE), 9, 9) END)

FROM PURTA AS A
INNER JOIN PURTB AS B ON TC001 = TD001 AND TC002 = TD002
WHERE 1=1 
-- AND LEFT(A.CREATE_DATE, 6) >= '202101' 
AND TC003 >= '20210101'
AND (LEFT(B.CREATE_DATE, 8) > TC003 OR LEFT(A.CREATE_DATE, 8) > TC003)
-- AND TC001 = '2201' AND TC002 = '2101001'
-- AND (CASE WHEN RTRIM(A.MODI_DATE) = '' THEN A.MODI_DATE ELSE RTRIM(TC003)+SUBSTRING(RTRIM(A.MODI_DATE), 9, 9) END) < RTRIM(TC003)+SUBSTRING(RTRIM(A.CREATE_DATE), 9, 9)


ORDER BY TC001, TC002




---------------修改单头修改时间

SELECT TC001, TC002, TC003, 
SUBSTRING(A.CREATE_DATE, 9, 2) ACS, SUBSTRING(A.MODI_DATE, 9, 2) AMS, 
RIGHT('000' + CAST(CAST(SUBSTRING(A.CREATE_DATE, 9, 2) AS INT) + 1 AS VARCHAR(2)), 2) AMSN,  
(CASE WHEN SUBSTRING(A.CREATE_DATE, 9, 2) = '23' THEN SUBSTRING(A.CREATE_DATE, 1, 8) + SUBSTRING(A.CREATE_DATE, 9, 2) + SUBSTRING(A.MODI_DATE, 11, 7)
	ELSE SUBSTRING(A.CREATE_DATE, 1, 8) + RIGHT('000' + CAST(CAST(SUBSTRING(A.CREATE_DATE, 9, 2) AS INT) + 1 AS VARCHAR(2)), 2) + SUBSTRING(A.MODI_DATE, 11, 7) END)
 
-- UPDATE PURTA SET PURTA.MODI_DATE = (CASE WHEN SUBSTRING(A.CREATE_DATE, 9, 2) = '23' THEN SUBSTRING(A.CREATE_DATE, 1, 8) + SUBSTRING(A.CREATE_DATE, 9, 2) + SUBSTRING(A.MODI_DATE, 11, 7) ELSE SUBSTRING(A.CREATE_DATE, 1, 8) + RIGHT('000' + CAST(CAST(SUBSTRING(A.CREATE_DATE, 9, 2) AS INT) + 1 AS VARCHAR(2)), 2) + SUBSTRING(A.MODI_DATE, 11, 7) END)

FROM PURTA AS A
INNER JOIN PURTB AS B ON TC001 = TD001 AND TC002 = TD002
WHERE 1=1 
AND TC003 >= '20210101'
AND A.MODI_DATE < A.CREATE_DATE 
AND RTRIM(A.MODI_DATE) != '' 

ORDER BY TC001, TC002


--------------- 修改单身修改时间

SELECT TC001, TC002, TC003, 
SUBSTRING(B.CREATE_DATE, 9, 2) ACS, SUBSTRING(B.MODI_DATE, 9, 2) AMS, 
RIGHT('000' + CAST(CAST(SUBSTRING(B.CREATE_DATE, 9, 2) AS INT) + 1 AS VARCHAR(2)), 2) AMSN,  
(CASE WHEN SUBSTRING(B.CREATE_DATE, 9, 2) = '23' THEN SUBSTRING(B.CREATE_DATE, 1, 8) + SUBSTRING(B.CREATE_DATE, 9, 2) + SUBSTRING(B.MODI_DATE, 11, 7)
	ELSE SUBSTRING(B.CREATE_DATE, 1, 8) + RIGHT('000' + CAST(CAST(SUBSTRING(B.CREATE_DATE, 9, 2) AS INT) + 1 AS VARCHAR(2)), 2) + SUBSTRING(B.MODI_DATE, 11, 7) END)
 
-- UPDATE PURTB SET PURTB.MODI_DATE = (CASE WHEN SUBSTRING(B.CREATE_DATE, 9, 2) = '23' THEN SUBSTRING(B.CREATE_DATE, 1, 8) + SUBSTRING(B.CREATE_DATE, 9, 2) + SUBSTRING(B.MODI_DATE, 11, 7) ELSE SUBSTRING(B.CREATE_DATE, 1, 8) + RIGHT('000' + CAST(CAST(SUBSTRING(B.CREATE_DATE, 9, 2) AS INT) + 1 AS VARCHAR(2)), 2) + SUBSTRING(B.MODI_DATE, 11, 7) END)

FROM PURTA AS A
INNER JOIN PURTB AS B ON TC001 = TD001 AND TC002 = TD002
WHERE 1=1 
AND TC003 >= '20210101'
AND B.MODI_DATE < B.CREATE_DATE 
AND RTRIM(B.MODI_DATE) != '' 

ORDER BY TC001, TC002
