CREATE OR REPLACE PROCEDURE SCOTT.P_TEST
as 
begin 

	INSERT INTO TEST(A1, A2) VALUES('1', '2' );
	COMMIT;
	DBMS_OUTPUT.PUT_LINE('SUCCES');

end P_TEST;


CREATE OR REPLACE PROCEDURE SCOTT.P_TEST_2 (V1 in SCOTT.TEST.A1%type DEFAULT '3', V2 in SCOTT.TEST.A2%type DEFAULT '4')
as 
begin 

	INSERT INTO TEST(A1, A2) VALUES(V1, V2);
	COMMIT;
	DBMS_OUTPUT.PUT_LINE('SUCCES');

end P_TEST_2;



-- CREATE TABLE SCOTT.TEST (A1 VARCHAR2(20), A2 VARCHAR2(20));


BEGIN
 SCOTT.P_TEST_2 ('20', '30');
END;




SELECT * FROM SCOTT.TEST;