-----99
--公司帐套
USE [COMFORT]
GO
ALTER DATABASE COMFORT SET RECOVERY SIMPLE WITH NO_WAIT
GO
ALTER DATABASE COMFORT SET RECOVERY SIMPLE  
GO
USE COMFORT 
GO
DBCC SHRINKFILE (N'Leader_Log' , 11, TRUNCATEONLY)
GO
USE [COMFORT]
GO
ALTER DATABASE COMFORT SET RECOVERY FULL WITH NO_WAIT
GO
ALTER DATABASE COMFORT SET RECOVERY FULL  
GO
--公共资料库
USE [DSCSYS]
GO
ALTER DATABASE DSCSYS SET RECOVERY SIMPLE WITH NO_WAIT
GO
ALTER DATABASE DSCSYS SET RECOVERY SIMPLE  
GO
USE DSCSYS 
GO
DBCC SHRINKFILE (N'DSCSYS_Log' , 11, TRUNCATEONLY)
GO
USE [DSCSYS]
GO
ALTER DATABASE DSCSYS SET RECOVERY FULL WITH NO_WAIT
GO
ALTER DATABASE DSCSYS SET RECOVERY FULL  
GO


-----239
--公司帐套
USE [Comfortseating]
GO
ALTER DATABASE Comfortseating SET RECOVERY SIMPLE WITH NO_WAIT
GO
ALTER DATABASE Comfortseating SET RECOVERY SIMPLE  
GO
USE Comfortseating 
GO
DBCC SHRINKFILE (N'Leader_Log' , 11, TRUNCATEONLY)
GO
USE Comfortseating
GO
ALTER DATABASE Comfortseating SET RECOVERY FULL WITH NO_WAIT
GO
ALTER DATABASE Comfortseating SET RECOVERY FULL  
GO
--公共资料库
USE [DSCSYS]
GO
ALTER DATABASE DSCSYS SET RECOVERY SIMPLE WITH NO_WAIT
GO
ALTER DATABASE DSCSYS SET RECOVERY SIMPLE  
GO
USE DSCSYS 
GO
DBCC SHRINKFILE (N'DSCSYS_Log' , 11, TRUNCATEONLY)
GO
USE [DSCSYS]
GO
ALTER DATABASE DSCSYS SET RECOVERY FULL WITH NO_WAIT
GO
ALTER DATABASE DSCSYS SET RECOVERY FULL  
GO







--99

--报表数据
USE [report]
GO
ALTER DATABASE report SET RECOVERY SIMPLE WITH NO_WAIT
GO
ALTER DATABASE report SET RECOVERY SIMPLE  
GO
USE report 
GO
DBCC SHRINKFILE (N'report_Log' , 11, TRUNCATEONLY)
GO
USE [report]
GO
ALTER DATABASE report SET RECOVERY FULL WITH NO_WAIT
GO
ALTER DATABASE report SET RECOVERY FULL  
GO

--公共资料库
USE [TEST2018]
GO
ALTER DATABASE TEST2018 SET RECOVERY SIMPLE WITH NO_WAIT
GO
ALTER DATABASE TEST2018 SET RECOVERY SIMPLE  
GO
USE TEST2018 
GO
DBCC SHRINKFILE (N'TEST2018_Log' , 11, TRUNCATEONLY)
GO
USE [TEST2018]
GO
ALTER DATABASE TEST2018 SET RECOVERY FULL WITH NO_WAIT
GO
ALTER DATABASE TEST2018 SET RECOVERY FULL  